version: "3.8"

services:
  blazorapp:
    build:
      target: final
    tty: true
    ports:
      - 8080:80
    restart: on-failure
    depends_on: 
      - postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"
